/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#002028',
        'on-primary': '#ffffff',
        'primary-container': '#0a3641',
        'on-primary-container': '#799fac',
        'primary-fixed': '#c1e9f7',
        'primary-fixed-dim': '#a5cdda',
        'on-primary-fixed': '#001f27',
        'on-primary-fixed-variant': '#254c57',
        'inverse-primary': '#a5cdda',

        'secondary': '#376757',
        'on-secondary': '#ffffff',
        'secondary-container': '#baeed9',
        'on-secondary-container': '#3d6d5d',
        'secondary-fixed': '#baeed9',
        'secondary-fixed-dim': '#9ed1bd',
        'on-secondary-fixed': '#002117',
        'on-secondary-fixed-variant': '#1d4f40',

        'tertiary': '#00211d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#003832',
        'on-tertiary-container': '#3ba99b',
        'tertiary-fixed': '#8cf5e4',
        'tertiary-fixed-dim': '#6fd8c8',
        'on-tertiary-fixed': '#00201c',
        'on-tertiary-fixed-variant': '#005048',

        'surface': '#f9f9ff',
        'surface-dim': '#cfdaf2',
        'surface-bright': '#f9f9ff',
        'surface-variant': '#d8e3fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eeff',
        'surface-container-high': '#dee8ff',
        'surface-container-highest': '#d8e3fb',
        'surface-tint': '#3e6470',

        'on-surface': '#111c2d',
        'on-surface-variant': '#41484a',
        'inverse-surface': '#263143',
        'inverse-on-surface': '#ecf1ff',

        'outline': '#71787b',
        'outline-variant': '#c1c8cb',

        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        'background': '#f9f9ff',
        'on-background': '#111c2d',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        full: '9999px',
      },
      spacing: {
        'margin': '1.5rem',
        'margin-mobile': '1rem',
        'margin-desktop': '3rem',
        'gutter': '1.5rem',
        'gutter-sm': '1rem',
        'gutter-lg': '2rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['30px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
